name: Cypress API Tests
on:
    pull_request:
        branches: [main]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6